name: Deploy

on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_UPDATE_URL }}
          headers: '{"X-AUTH-TOKEN": "${{ secrets.NEXT_AUTH_TOKEN }}"}'
